### PR TITLE
Fix token response parsing

### PR DESCRIPTION
**Pull request by tr4nt0r**
- Removed unnecessary rounding in token expiration check.
- Updated token parsing to align with API response structure.
- Adjusted `GetTokenResponse` typing attributes accordingly.

#### Add GitHub Actions workflow for pytest

- Introduced GitHub Actions workflow for running tests on push and pull requests.
- Configured matrix strategy to test with Python versions 3.11 and 3.12.
- Installed project dependencies and ran pytest with coverage reporting.
- Integrated Codecov for coverage reporting using a GitHub Actions workflow.

### CODE REVIEW

**Comment by Ludy87** [comment]
Always consider compatibility with: https://github.com/Ludy87/ecotrend-ista

**Comment by tr4nt0r** [comment]
> Always consider compatibility with: https://github.com/Ludy87/ecotrend-ista

Sure, always trying to keep in mind not to change the public API, that's why i add aliases for backwards-compatibility. Purely internal methods will not need the compatibility layer.

By the way, I'm also using this library for a HA core integration that will debut in the 2024.7.0 release 😉

**Comment by tr4nt0r** [comment]
Damn, the pytest was not in the commit 🙈

**Comment by Ludy87** [comment]
> > Always consider compatibility with: https://github.com/Ludy87/ecotrend-ista
> 
> Sure, always trying to keep in mind not to change the public API, that's why i add aliases for backwards-compatibility. Purely internal methods will not need the compatibility layer.
> 
> By the way, I'm also using this library for a HA core integration that will debut in the 2024.7.0 release 😉

Dann kann ich die Integration Archivieren

**Comment by tr4nt0r** [comment]
> > > Always consider compatibility with: https://github.com/Ludy87/ecotrend-ista
> > 
> > 
> > Sure, always trying to keep in mind not to change the public API, that's why i add aliases for backwards-compatibility. Purely internal methods will not need the compatibility layer.
> > By the way, I'm also using this library for a HA core integration that will debut in the 2024.7.0 release 😉
> 
> Dann kann ich die Integration Archivieren

Nun, für Core integrationen ist es immer ein längerer Prozess, bis alle features drin sind, also noch sind es nur ein paar Sensoren, re-auth flow fehlt, 2FA Support fehlt. Also ist die custom integration vom Funktionsumfang noh weit voraus.

**Comment by tr4nt0r** [comment]
Habe noch ne Github action dran gehängt, die pytest laufen lässt und wenn du Codecov token im repo konfigurierst, sollte es auch den coverage report hochladen

**Review by Ludy87 — APPROVED** [review]

**Review by Ludy87 — APPROVED** [review]

**Pull request merged**
